### ISSUE TITLE
`this.onFinish is not a function`

### ISSUE THREAD

**Issue by dfreeman** [testem/testem#1056]
Since updating to 1.14, I've started seeing `this.onFinish is not a function` errors from time to time stemming from `browser_test_runner.js`.

To be honest, I'm not familiar with the testem internals, and I'm a little murky on the exact sequence of events that's leading to this scenario, but I'm guessing that [this change](https://github.com/testem/testem/commit/2561a84b572fe8c82aeb214d721f4bca8315522e#diff-5eae7e485342946ae50eea2a59770c09R302) is likely the culprit. The call to `this.onFinish()` a few lines above is guarded on the truthiness of `onFinish`, and I'm guessing `this.exit()` is happy to receive an undefined callback, but the new `then()` handler just assumes it's defined.

Would just adding a guard there be reasonable, or is it expected that `onFinish` should always be defined at that point?

**Comment by getsnoopy** [comment]
@dfreeman yes, that seems to be the issue. when i add a similar guard in the `return` statement, the error goes away.

**Comment by johanneswuerbach** [comment]
Sounds good, would happily accept a PR :-)
